apiVersion: apps/v1
kind: Deployment
metadata:
  name: activator
  namespace: knative-serving
spec:
  template:
    spec:
      # Must stay >= config-defaults' max-revision-timeout-seconds.
      terminationGracePeriodSeconds: 1800
