apiVersion: v1
data:
  providers: |-
    s3:
      default:
        endpoint: s3.us-west-2.amazonaws.com
        disableSSL: false
        region: us-west-2
        forcePathStyle: true
        credentials:
          fromEnv: true
kind: ConfigMap
metadata:
  name: kfp-launcher
