apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- kubeflow-tls-certificate.yaml
- istio-ingressgateway-idle-timeout.yaml

components:
- ../../../../oauth2-proxy/components/istio-external-auth-patches

patches:
- path: istio-ingressgateway-lb-patch.yaml